### ISSUE TITLE
Xbee USB Error: timeout fetching DDO parameter (HV@None)

### ISSUE THREAD

**Issue by David-bfg** [jordanh/cp4pc#8]
I have been running into a funny issue where my USB xbib-u-dev board seems to be singled out as the cause of this error.

I have tried this on both linux and windows to run cp4pc with the USB connector for xbee. I can only run this successfully using the serial port connector. I only have 2 types of connectors, one serial board and two USB boards. Each works just fine with x-cut so they are all functional.

It would be cool if you guys could give me some options for debugging this. Since this project has not been active for a while a list of known good connectors to use with USB would help me out here.

Thanks.

**Comment by mikewadsten** [comment]
@David-bfg: It sounds like either:
- The XBee is in AT mode, not API mode (cp4pc communicates with the XBee in API mode), or
- There's some other issue with communicating with the XBee.

~~Are you able to use XCTU to configure the XBee when using the XBIB-U? If so,~~

Make sure the AP parameter is set to 1.

~~If you can't configure the XBee with XCTU (i.e. XCTU cannot find the radio), then~~

Perhaps use pdb to walk through the execution of the `read_messages` function (zigbee.py line 1240) and see the data in `self.rx_buffer`. (You could also add `print repr(self.rx_buffer)` between lines 1248 and 1249 and just watch the console output.)

**Edit:** I realize now that you meant X-CTU instead of "x-cut". I've struck out the relevant portion of my comment.

**Comment by David-bfg** [comment]
@mikewadsten When logging the value of <code>self.rx_buffer</code> it will respond by continually printing an empty string.

Fiddling around on my own I was able to get my xbee module into a working state by moving it from the serial board to the USB board. After that it seems to be in a working state.

I can recreate the error again if I mess around with X-CTU. Not sure exactly what happens but at some point it gets stuck in a non responsive state when trying to use cp4pc. So I'm just gonna stop configuring it with X-CTU for the moment and live with how it seems to be working now.

Still not sure of the exact cause but suspect it might be having X-CTU and cp4pc running at the same time.

**Comment by tomlogic** [comment]
@David-bfg, if you have the serial port open in X-CTU, that would prevent cp4pc from opening the port.  If that's case, it's a bug that cp4pc doesn't detect the failure and report it before exiting.

**Comment by mikewadsten** [comment]
@tomlogic, @David-bfg: One thing that I remember always happening with cp4pc is seeing an error message due to the logger not being configured. In the `open_com_thread` function the exception opening the port would be caught and logged, but without a logger you won't see anything.

@David-bfg: If you replace the `print repr(self.rx_buffer)` line with:

```
print self.serial, (self.serial.isOpen() if self.serial else False), self.rx_buffer
```

you'd be able to see if self.serial is None or not. `self.serial` being None would explain always seeing an empty buffer. I might also try adding

```
import logging
logging.basicConfig()
```

to your code (if you don't already use the standard logging mechanism), and see if you get "`Exception while creating serial port (<com>, <baud>): <some error>`".
